name: 'Spellcheck'
description: 'This action runs a spellcheck on the specified files'
inputs:
  files-changed:
    default: '**/*'
    description: Files changed
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}