name: 'Spellcheck Action'
description: 'This action runs a spellcheck on the specified files'
inputs:
  files-changed:
    default: '**/*'
    description: Files changed
    required: false
  GITHUB_TOKEN:
    required: true
  issue_number:
    required: true
  owner:
    required: true
  repo:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'